### ISSUE TITLE
Support GitHub's new `repositories` parameter

### ISSUE THREAD

**Issue by martinbaillie** [martinbaillie/vault-plugin-secrets-github#36]
Since the creation of this plugin, GitHub has improved the App installation token request payloads to be easier to use. You no longer have to call out repository IDs and can instead use the friendly name of the repository.

Make this parameter a first class citizen in the plugin.

---

SEE: https://docs.github.com/en/rest/reference/apps#create-an-installation-access-token-for-an-app

**Comment by grahamc** [comment]
One down side is this means permissions can migrate to new repositories
after renames. Not a very general concern, but very paranoid deployments
may want to stick to IDs. I’m looking forward to skipping the IDs!

On May 20, 2021, GitHub ***@***.***> wrote:
> Since the creation of this plugin, GitHub has improved the App
> installation token request payloads to be easier to use. You no longer
> have to call out repository IDs and can instead use the friendly name
> of the repository.
>
> Make this parameter first class citizen in the plugin.
>

> SEE: <https://docs.github.com/en/rest/reference/apps#create-an-
> installation-access-token-for-an-app>
>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/martinbaillie/vault-plugin-secrets-
github/issues/36>, or unsubscribe
<https://github.com/notifications/unsubscribe-
auth/AAASXLGSY223PLERXQSDK33TOXNUDANCNFSM45ILUB5Q>.

**Comment by martinbaillie** [comment]
Great point! 🤯 

I'll be sure to document that caveat when it gets implemented.

**Comment by martinbaillie** [comment]
This field is now supported in the https://github.com/martinbaillie/vault-plugin-secrets-github/releases/tag/v1.2.0.
