### ISSUE TITLE
error disabling a github secret engine mount

### ISSUE THREAD

**Issue by raffaelespazzoli** [martinbaillie/vault-plugin-secrets-github#59]
I'm getting the following error wehn disabling a mount:
```
2022-01-11T02:16:39.438Z [ERROR] secrets.vault-plugin-secrets-github.vault-plugin-secrets-github_5693eb2d.vault-plugin-secrets-github.vault-plugin-secrets-github-linux-amd64: plugin tls init: error="error during token unwrap request: Put \"https://10.130.7.188:8200/v1/sys/wrapping/unwrap\": x509: cannot validate certificate for 10.130.7.188 because it doesn't contain any IP SANs" timestamp=2022-01-11T02:16:39.438Z
2022-01-11T02:16:39.439Z [ERROR] rollback: error rolling back: path=github/
  error=
  | Unrecognized remote plugin message:
  |
  | This usually means that the plugin is either invalid or simply
  | needs to be recompiled to support the latest protocol.
```
I'm using vault 1.9.0.

who is trying to validate a connection from whom? And which client certificate is this referring to? I have none, is this the ssh key?
I'm running this in a Kubernetes pod and `10.130.7.188` is the IP of the pod.

Can you provide some guidance on this?

**Comment by raffaelespazzoli** [comment]
so I am getting this error also on other operations. It looks like the plugin calls a Vault endpoint and cannot validate the certificate... Is there a way to pass a CA to the plugin so to trust the certificate presented by the Vault server?

**Comment by raffaelespazzoli** [comment]
I think I figured this out, there are a few undocumented parameters that can be passed to the plugin executable to deal with certs. I suggest documenting these parameters.

**Comment by grahamc** [comment]
I'm not sure the source of this issue, but I've not seen issues enabling/using/disabling the plugin, and I haven't need to use any undocumented parameters. Nor have I needed to do anything around certs. Can you share what you ended up doing?

**Comment by raffaelespazzoli** [comment]
my understanding is that the plugin talks back to vault and if vault does not exposes a trusted cert the plugins needs some additional configuration. In my case I ended up adding this: `-args="--tls-skip-verify=true"` to the plugin registration command.

**Comment by martinbaillie** [comment]
My read of that specific error is you're trying to talk TLS to a Vault instance by IP address, and that IP address is not present as an IP SAN extension in the certificate presented by your Vault. Perhaps there's a hostname you should be using.

For general CA issues, you can try ensuring your private CA is in the system's SSL certs, or environment variables of the process like `VAULT_CACERT` or `SSL_CERT_FILE`.

**Comment by dhess** [comment]
FYI, I've been using this plugin for about a year on an EC2 Vault cluster, and now that I'm moving to Kubernetes, I'm experiencing the same issue.

If you install Vault on a Kubernetes cluster via the Helm chart, which is what Hashicorp recommend, then in a Raft HA setup, inevitably the plugin will end up trying to communicate with the leader directly via its IP address. This IP address will most likely be from a fairly large private subnet, and it's not practical to enumerate the entire subrange in the cluster's IP SAN extension (unless the extension supports CIDR notation? AFAIK it does not.)

Due to the recommendation that you run a layer 3 load balancer in front of a Kubernetes Vault HA cluster (to preserve end-to-end TLS from the client to the leader), the leader does not have a predictable DNS name. Additionally, the load balancer IP generally won't be known until after the cluster is created, and its IP can change in some circumstances (e.g., if you reconfigure the cluster), so it's not practical to use that IP for the plugin, either.

As far as I know, then, this configuration requires some additional setup, and it would be nice if it were documented.
